# Generated by Django 4.2.2 on 2025-03-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='DOB',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
    ]
